import "./globals.css";

import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { NextAuthProvider } from "@/components/providers";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });

export const metadata = {
  title: "Learn something new every week | Basecasts",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <NextAuthProvider>
          {children}
          <Analytics />
        </NextAuthProvider>
      </body>
    </html>
  );
}
