import "./globals.css";

import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { NextAuthProvider } from "@/components/providers";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });

export const metadata = {
  title: "Learn something new every week | Basecasts",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <NextAuthProvider>
          <Header />
          {children}
          <Footer />
          <Analytics />
        </NextAuthProvider>
      </body>
    </html>
  );
}
