import { graphql } from "@/gql";
import type {
  IndexPageQueryQuery,
  IndexPageQueryQueryVariables,
} from "@/gql/graphql";
import { grafbase } from "@/lib/grafbase";

import { Hero } from "@/components/hero";
import { EpisodeList } from "@/components/episode-list";

export const metadata = {
  title: "Learn something new every week | Basecasts",
  description: "Generated by create next app",
};

const IndexPageQuery = graphql(/* GraphQL */ `
  query IndexPageQuery($first: Int) {
    episodeCollection(first: $first, orderBy: { createdAt: DESC }) {
      ...EpisodeList_EpisodeConnectionFragment
    }
  }
`);

export default async function Page() {
  const { episodeCollection } = await grafbase.request<
    IndexPageQueryQuery,
    IndexPageQueryQueryVariables
  >(IndexPageQuery.toString(), { first: 3 });

  return (
    <>
      <div className="px-6 lg:px-8 space-y-6 md:space-y-12 lg:space-y-20">
        <Hero />

        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-base font-semibold leading-7 text-green-500">
            Updated weekly
          </h2>
          <p className="text-3xl md:text-4xl font-bold tracking-tight text-black sm:text-4xl">
            Latest episodes
          </p>
        </div>

        <div className="mx-auto max-w-5xl py-8 md:py-16">
          {/* lessonCollection is not of the type EpisodeList_LessonConnectionFragment dur */}
          <EpisodeList query={episodeCollection} />
        </div>
      </div>
    </>
  );
}
